// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackXpert_API.Data;

#nullable disable

namespace TrackXpert_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackXpert_API.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Genres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SocialLinks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("TrackXpert_API.Models.TrackArtist", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ArtistId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackArtists");
                });

            modelBuilder.Entity("TrackXpert_API.Models.TrackData.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("TrackXpert_API.Models.TrackArtist", b =>
                {
                    b.HasOne("TrackXpert_API.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackXpert_API.Models.TrackData.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TrackXpert_API.Models.TrackData.Track", b =>
                {
                    b.OwnsOne("TrackXpert_API.Models.TrackData.TrackAnalytics", "Analytics", b1 =>
                        {
                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FeedbackCount")
                                .HasColumnType("int");

                            b1.Property<int>("Likes")
                                .HasColumnType("int");

                            b1.Property<int>("PlaybackCount")
                                .HasColumnType("int");

                            b1.HasKey("TrackId");

                            b1.ToTable("Tracks");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.OwnsOne("TrackXpert_API.Models.TrackData.TrackFileInfo", "FileInfo", b1 =>
                        {
                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Format")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<string>("PreviewUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("UpdatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("UploadDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UploadedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WaveformData")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TrackId");

                            b1.ToTable("Tracks");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.OwnsOne("TrackXpert_API.Models.TrackData.TrackMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Bpm")
                                .HasColumnType("float");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Genre")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsExplicit")
                                .HasColumnType("bit");

                            b1.Property<string>("Key")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("ReleaseDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Tags")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TrackId");

                            b1.ToTable("Tracks");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.OwnsOne("TrackXpert_API.Models.TrackData.TrackProcessingStatus", "ProcessingStatus", b1 =>
                        {
                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ProcessingStatus")
                                .HasColumnType("int");

                            b1.HasKey("TrackId");

                            b1.ToTable("Tracks");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("Analytics");

                    b.Navigation("FileInfo");

                    b.Navigation("Metadata");

                    b.Navigation("ProcessingStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
